# gitlab configs
gitlab_url: 'https://git.self_hosted_gitlab.com/'
gitlab_private_token: '***********'

# k8s configs
k8s_config_filename: '~/.kube/config'
k8s_skip_keywords:
    - redis
    - databus
    - beat
    - flower
    - scaler
    - nginx
    - prometheus
    - proxy
    - keycloak
k8s_watch_timeout_seconds: 300
