namespaces:
    dev_01:
        k8s_name: ps-dev-01
        gitlab_name: dev-01

    dev_02:
        k8s_name: ps-dev-02
        gitlab_name: dev-02

    dev_03:
        k8s_name: ps-dev-03
        gitlab_name: dev-03

    dev_04:
        k8s_name: ps-dev-04
        gitlab_name: dev-04